customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('basket/',views.basket,name='basket'),
    path('login/',views.login_view,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('wish-product/<int:pk>/',views.wish_product,name='wish-product'),
    path('unwish-product/<int:pk>/',views.unwish_product,name='unwish-product'),
    path('add-basket/<int:product_pk>/',views.add_basket,name='add-basket'),
    path('increase-basket-item/<int:basket_pk>/',views.increase_basket_item,name='increase-basket-item'),
    path('decrease-basket-item/<int:basket_pk>/',views.decrease_basket_item,name='decrease-basket-item'),
    path('remove-basket/<int:basket_pk>/',views.remove_basket,name='remove-basket'),
    path('change-currency/',views.change_currency,name='change-currency'),
    path('forgot-password/',views.forgot_password_view,name='forgot-password'),
    path('reset-password/<str:token>/',views.reset_password_view,name='reset-password'),
    path('reset-password-result/<str:color>/<str:message>/',views.reset_password_result_view,name='reset-password-result'),
]

multishop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from.sitemaps import StaticViewSitemap,ProductViewSitemap
from django.contrib.sitemaps.views import sitemap
from . import views
from os import getenv


sitemaps = {
    'static': StaticViewSitemap,
    'product': ProductViewSitemap,
}

urlpatterns = [
    path(getenv('ADMIN_URL'), admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path('robots.txt', views.robots),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('',include('shop.urls')),
    path('customer/',include('customer.urls')),
    path('payment/',include('payment.urls')),
)

shop/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add-wish/<int:pk>/', views.add_wish, name='api-add-wish'),
    path('remove-wish/<int:pk>/', views.remove_wish, name='api-remove-wish'),
]   

shop/urls.py
from django.urls import path,include
from . import views


app_name='shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product-list'),
    path('products/<int:pk>/<str:slug>/', views.product_detail, name='product-detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('api/', include('shop.api.urls'))
]

shop/models.py
from django.db import models
from django.contrib.admin import display
from django.utils.html import format_html
from django.urls import reverse
from shared.urlutils import get_slug

# Create your models here.


class Size(models.Model):
    title = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.title


class GeneralCategory(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=20)
    image = models.ImageField(upload_to='categories')
    general_category = models.ForeignKey(
        GeneralCategory, on_delete=models.SET_NULL, null=True, blank=True, related_name='sub_categories')

    def __str__(self):
        return self.title


class Campaign(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    is_slider = models.BooleanField(default=False)
    image = models.ImageField(upload_to='campaigns')
    discount_percent = models.FloatField()

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.TextField(max_length=50)
    slug = models.CharField(max_length=100, blank=True)
    old_price = models.FloatField(null=True, blank=True)
    featured = models.BooleanField(default=True)
    price = models.FloatField()
    description = models.TextField()
    sizes = models.ManyToManyField(Size, related_name='products')
    colors = models.ManyToManyField(Color, related_name='products')
    category = models.ManyToManyField(Category, related_name='products')
    campaign = models.ManyToManyField(Campaign, related_name='products')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    general = models.ManyToManyField(GeneralCategory, related_name='products')

    def get_similar_products(self):
        similar_by_general = Product.objects.filter(
            general__in=self.general.all()).exclude(pk=self.pk)
        return similar_by_general

    def save(self, *args, **kwargs):
        self.slug = get_slug(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("shop:product-detail", kwargs={"pk": self.pk, 'slug': self.slug})

    def get_avg_star(self):
        return self.reviews.aggregate(star_count_avg=models.Avg('star_count'))['star_count_avg'] or 0


class ProductImage(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images')

    def __str__(self):
        return self.image.url

    @display(description="Movcud sekil")
    def image_tag(self):
        return format_html(f'<img width="200" src="{self.image.url}">')

shop/api/views.py
from django.http import JsonResponse
from ..models import Product
from customer.models import WishItem

def add_wish(request, pk):
    WishItem.objects.create(customer=request.user.customer,product_id=pk)
    return JsonResponse({'result':'added'})


def remove_wish(request, pk):
    WishItem.objects.filter(customer=request.user.customer,product_id=pk).delete()
    return JsonResponse({'result':'removed'})
    

shop/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
from .models import Campaign,Category,Product,Color,Size
from django.db.models import Count,Avg
from customer.models import Review
from django.core.paginator import Paginator
from django.contrib.postgres.search import TrigramSimilarity,SearchQuery,SearchRank,SearchVector
from .filters import ProductFilter
from django.views.decorators.cache import cache_page
# Create your views here.

# @cache_page(15)
def home(request):
    slide_campaigns=Campaign.objects.filter(is_slider=True)[:3]
    nonslide_campaigns=Campaign.objects.filter(is_slider=False)[:4]
    categories=Category.objects.annotate(product_count=Count('products'))
    featured_products=Product.objects.filter(featured=True)[:8]
    recent_products=Product.objects.all().order_by('-created')[:8]
    return render(request,'home.html',{
        "slide_campaigns": slide_campaigns,
        "nonslide_campaigns": nonslide_campaigns,
        "categories": categories,
        "featured_products": featured_products,
        "recent_products": recent_products,
    })

def product_list(request):
    products = Product.objects.all().annotate(avg_star=Avg('reviews__star_count'), review_count=Count('reviews'))

    search_input = request.GET.get('search')
    if search_input:
        # products = products.filter(title=search_input)
        # products = products.filter(title__iexact=search_input)
        # products = products.filter(title__icontains=search_input)
        # products = products.annotate(similarity=TrigramSimilarity('title', search_input)).filter(similarity__gt=0.2).order_by('-similarity')
        vector = SearchVector("title", weight="A") + SearchVector("description", weight="B") + SearchVector("category__title", weight="C")
        query = SearchQuery(search_input)
        products = products.annotate(rank=SearchRank(vector, query)).filter(rank__gte=0.1).order_by('-rank')

    product_filter = ProductFilter(request.GET, products)
    products = product_filter.qs

    sorting_input = request.GET.get('sorting')
    if sorting_input:
        if sorting_input == '-avg_star':
            products = products.order_by('-avg_star', '-review_count')
        else:
            products = products.order_by(sorting_input)


    page_by_input = int(request.GET.get('page_by', 4))
    page_input = request.GET.get('page', 1)
    paginator = Paginator(products, page_by_input)
    page = paginator.page(page_input)
    products = page.object_list

    colors = Color.objects.all().annotate(product_count=Count('products'))
    sizes = Size.objects.all().annotate(product_count=Count('products'))

    return render(request, 'product-list.html', {
        'products': products,
        'paginator': paginator,
        'page': page,
        'colors': colors,
        'sizes': sizes,
    })

def product_detail(request,pk,slug):
    product=get_object_or_404(Product,pk=pk)
    current_review=None
    if (request.user.is_authenticated and request.user.customer):
        current_review=Review.objects.filter(customer=request.user.customer,product=product).first()
    return render(request,'product-detail.html',{'product':product,'current_review':current_review})


def review(request,pk):
    if request.method == 'POST':
        customer=request.user.customer
        product = get_object_or_404(Product, pk=pk)
        if Review.objects.filter(customer=customer , product=product).exists():
            return HttpResponse(status=403)
        star_count = int(request.POST.get('star_count'))
        comment = request.POST.get('comment')
        Review.objects.create(
            customer=customer,
            product=product,
            star_count=star_count,
            comment=comment
        )
        return redirect('shop:product-detail', pk=product.pk,slug=product.slug)
    return redirect('shop:product-detail', pk=product.pk,slug=product.slug)
    
                         

shop/templates/home.html
 {% extends 'layout.html' %}
 {% load static %}
 {% load i18n %}
{% load cache %}

{% block meta_tags %}
<meta name="keywords" content="clothes , shop , online shop , shop online , wear">
<meta name="robots" content="index, follow">
<meta name="description" content="Welcome to your one-stop online shop! Discover a world of endless shopping possibilities at our online store. Explore curated collections, find your style.">
<meta property="og:title" content="Ana Səhifə - Compar Academy İxtisaslaşmış Tədris Mərkəzi">
<meta property="og:description" content="Məqsədimiz tədrisini etdiyimiz sahələrə marağı olan insanlara motivasiya vermək, düzgün istiqamətləndirmək və gələcəklərinə müsbət təsir göstərməkdir.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://compar.edu.az/en/">
<meta property="og:image" content="/staticfiles/defaults/img/compar%20logo1%402x.png">
{% endblock meta_tags %}

 {% block main %}
    <header></header>
    <nav></nav>
    <main></main>
    <aside></aside>

 <!-- Carousel Start -->

 {% cache 15 home_slider %}
    <div class="container-fluid mb-3">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#header-carousel" data-slide-to="1"></li>
                        <li data-target="#header-carousel" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        {% for campaign in slide_campaigns %}
                        <div class="carousel-item position-relative {% if forloop.first %}active{% endif %}" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="{{campaign.image.url}}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">{{campaign.title}}</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">{{campaign.description}}</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">{% trans "Shop Now" %}</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                {% for campaign in nonslide_campaigns|slice:"0:2" %}
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{{campaign.image.url}}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save {{campaign.discount_percent|floatformat}}%</h6>
                        <h3 class="text-white mb-3">{{campaign.title}}</h3>
                        <a href="" class="btn btn-primary">{% trans "Shop Now" %}</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endcache %}
<!-- Carousel End -->


<!-- Featured Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5 pb-3">
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">{% trans "Quality Product" %}</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                <h5 class="font-weight-semi-bold m-0">{% trans "Free Shipping" %}</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">{% trans "14-Day Return" %}</h5>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
            <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                <h5 class="font-weight-semi-bold m-0">{% trans "24/7 Support" %}</h5>
            </div>
        </div>
    </div>
</div>
<!-- Featured End -->


<!-- Categories Start -->
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">{% trans "Categories" %}</span></h2>
    <div class="row px-xl-5 pb-3">
        {% for category in categories %}
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <a class="text-decoration-none" href="">
                <div class="cat-item d-flex align-items-center mb-4">
                    <div class="overflow-hidden" style="width: 100px; height: 100px;">
                        <img class="img-fluid" src="{{category.image.url}}" alt="">
                    </div>
                    <div class="flex-fill pl-3">
                        <h6>{{category.title}}</h6>
                        <small class="text-body">{{category.product_count}}</small>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Categories End -->


<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Featured Products</span></h2>

    <div class="row px-xl-5"> 
{% for product in featured_products %}
{% include 'includes/product-cart.html' with product=product %}
{% endfor %}

    </div>
</div>

<!-- Products End -->

<!-- Offer Start -->
<div class="container-fluid pt-5 pb-3">
    <div class="row px-xl-5">
        {% for campaign in nonslide_campaigns|slice:"2:" %}
        <div class="col-md-6">
            <div class="product-offer mb-30" style="height: 300px;">
                <img class="img-fluid" src="{{campaign.image.url}}" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save {{campaign.discount_percent}}%</h6>
                    <h3 class="text-white mb-3">{{campaign.title}}</h3>
                    <a href="" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- Offer End -->

<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Recent Products</span></h2>
    <div class="row px-xl-5">
        {% for product in recent_products %}
        {% include 'includes/product-cart.html' with product=product %}
        {% endfor %}
    </div>
</div>
<!-- Products End -->


{% endblock main %}

shop/templates/product-detail.html
{% extends 'layout.html' %}
{% load shop_helper %}
{% load static %}
{% block main %}
    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="#">Home</a>
                    <a class="breadcrumb-item text-dark" href="#">Shop</a>
                    <span class="breadcrumb-item active">Shop Detail</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">
                <div id="product-carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner bg-light">
                        {% for product_image in product.images.all  %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}">
                            <img class="w-100 h-100" src="{{product_image.image.url}}" alt="Image">
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" href="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>
            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{product.title}}</h3>
                    <div class="d-flex mb-3">
                        <div class="text-primary mr-2">
                            {% star product.get_avg_star %}
                        </div>
                        <small class="pt-1">(99 Reviews)</small>
                    </div>
                    {% if product.old_price %}
                    <h3 class="font-weight-semi-bold mb-4">{{product.price}} <del class="ml-3">{{product.old_price}}</del></h3>
                    {% else %}
                    <h3>{{product.price}}</h3>
                    {% endif %}
                    <p class="mb-4">{{product.description}}</p>
                    <form method="POST" action="{% url 'customer:add-basket' product_pk=product.pk %}">
                        {% csrf_token %}
                        <div class="d-flex mb-3">
                            <strong class="text-dark mr-3">Sizes:</strong>
                            {% for size in product.sizes.all %}
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input required type="radio" class="custom-control-input" id="size-{{size.pk}}" name="size" value="{{size.pk}}">
                                    <label class="custom-control-label" for="size-{{size.pk}}">{{size.title}}</label>
                                </div>
                                {% endfor %}
                        </div>
                        <div class="d-flex mb-4">
                            <strong class="text-dark mr-3">Colors:</strong>
                                {% for color in product.colors.all  %}
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input required type="radio" class="custom-control-input" id="color-{{color.pk}}" name="color" value="{{color.pk}}">
                                    <label class="custom-control-label" for="color-{{color.pk}}">{{color.title}}</label>
                                </div>
                                {% endfor %}
                        </div>
                        <div class="d-flex align-items-center mb-4 pt-2">
                            <div class="input-group quantity mr-3" style="width: 130px;">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-primary btn-minus">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control bg-secondary border-0 text-center" name="count" value="1" min="1">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary px-3 mr-3"><i class="fa fa-shopping-cart mr-1"></i> Add To
                                Cart</button>
                            </form>
                            <form method="POST" action="{% url 'customer:wish-product' pk=product.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary px-3"><i class="fas fa-heart"></i> Add To
                                    Wishlist</button>
                                </form>
                            </div>
                    <div class="d-flex pt-2">
                        <strong class="text-dark mr-2">Share on:</strong>
                        <div class="d-inline-flex">
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                            <a class="text-dark px-2" href="">
                                <i class="fab fa-pinterest"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-3">Reviews</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-1">Description</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade" id="tab-pane-1">
                            <h4 class="mb-3">Product Description</h4>
                            <p>Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.</p>
                            <p>Dolore magna est eirmod sanctus dolor, amet diam et eirmod et ipsum. Amet dolore tempor consetetur sed lorem dolor sit lorem tempor. Gubergren amet amet labore sadipscing clita clita diam clita. Sea amet et sed ipsum lorem elitr et, amet et labore voluptua sit rebum. Ea erat sed et diam takimata sed justo. Magna takimata justo et amet magna et.</p>
                        </div>
                        <div class="tab-pane fade show active" id="tab-pane-3">
                            <div class="row">
                                {% if current_review %}
                                <div class="col-md-6">
                                    <h4 class="mb-4">1 review for "Product Name"</h4>
                                    <div class="media mb-4">
                                        <img src="{% static 'img/user.jpg' %}" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                        <div class="media-body">
                                            <h6>{{request.user.get_full_name}}<small> - <i>{{current_review.created}}</i></small></h6>
                                            <div class="text-primary mb-2">
                                                {% star current_review.star_count %}
                                            </div>
                                            <p>{{current_review.comment}}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                <div class="col-md-6">
                                    {% if request.user.is_authenticated and not current_review %}
                                    <h4 class="mb-4">Leave a review</h4>
                                    <small>Your email address will not be published. Required fields are marked *</small>
                                    <form method="POST" action="{% url 'shop:review' pk=product.pk %}">
                                    {% csrf_token %}
                                    <div class="d-flex my-3">
                                        <p class="mb-0 mr-2">Your Rating * :</p>
                                        <div class="text-primary">
                                            <select name="star_count" id="">
                                                <option value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="message">Your Review Comment *</label>
                                        <textarea id="message" name="comment" cols="30" rows="5" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group mb-0">
                                        <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                    </div>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->


    <!-- Products Start -->
    <div class="container-fluid py-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">You May Also Like</span></h2>
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel related-carousel">
                {% for similar in similar_products %}
                    <div class="product-item bg-light">
                        <div class="product-img position-relative overflow-hidden">
                            <img class="img-fluid w-100" style={{"height:200px;object-fit:cover"}} src="{{similar.images.first.image.url}}" alt="">
                            <div class="product-action">
                                <a class="btn btn-outline-dark btn-square" href="{{product.get_absolute_url}}"><i class="fa fa-shopping-cart"></i></a>
                                <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                                <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                            </div>
                        </div>
                        <div class="text-center py-4">
                            <a class="h6 text-decoration-none text-truncate" href="{{product.get_absolute_url}}">{{similar.title}}</a>
                            <div class="d-flex align-items-center justify-content-center mt-2">
                                <h5>{{similar.price}}</h5><h6 class="text-muted ml-2"><del>{{similar.old_price}}</del></h6>
                            </div>
                            <div class="d-flex align-items-center justify-content-center mb-1">
                                {% star similar.get_avg_star %}          
                                <small>{{total_view}}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Products End -->
{% endblock main %}