customer/urls.py
from django.urls import path
from . import views

app_name='customer'

urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('wishlist/',views.wishlist_view,name='wishlist'),
    path('basket/',views.basket,name='basket'),
    path('login/',views.login_view,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout_view,name='logout'),
    path('wish-product/<int:pk>/',views.wish_product,name='wish-product'),
    path('unwish-product/<int:pk>/',views.unwish_product,name='unwish-product'),
    path('add-basket/<int:product_pk>/',views.add_basket,name='add-basket'),
    path('increase-basket-item/<int:basket_pk>/',views.increase_basket_item,name='increase-basket-item'),
    path('decrease-basket-item/<int:basket_pk>/',views.decrease_basket_item,name='decrease-basket-item'),
    path('remove-basket/<int:basket_pk>/',views.remove_basket,name='remove-basket'),
    path('change-currency/',views.change_currency,name='change-currency'),
    path('forgot-password/',views.forgot_password_view,name='forgot-password'),
    path('reset-password/<str:token>/',views.reset_password_view,name='reset-password'),
    path('reset-password-result/<str:color>/<str:message>/',views.reset_password_result_view,name='reset-password-result'),
]

multishop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from.sitemaps import StaticViewSitemap,ProductViewSitemap
from django.contrib.sitemaps.views import sitemap
from . import views
from os import getenv


sitemaps = {
    'static': StaticViewSitemap,
    'product': ProductViewSitemap,
}

urlpatterns = [
    path(getenv('ADMIN_URL'), admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path('robots.txt', views.robots),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + i18n_patterns(
    path('',include('shop.urls')),
    path('customer/',include('customer.urls')),
    path('payment/',include('payment.urls')),
)

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('checkout/',views.checkout,name='checkout'),
]

shop/urls.py
from django.urls import path,include
from . import views


app_name='shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.product_list, name='product-list'),
    path('products/<int:pk>/<str:slug>/', views.product_detail, name='product-detail'),
    path('review/<int:pk>/', views.review, name='review'),
    path('api/', include('shop.api.urls'))
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
from django.core.validators import MinValueValidator,MaxValueValidator
from uuid import uuid4
from django.utils import timezone
from django.utils.timezone import localtime,timedelta
from django.urls import reverse
from secrets import token_urlsafe
# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class WishItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,related_name='wishlist')
    created=models.DateField(auto_now_add=True)


class BasketItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    customer=models.ForeignKey('Customer',on_delete=models.CASCADE,related_name='basketlist')
    count=models.IntegerField(default=0)
    size=models.ForeignKey('shop.Size',on_delete=models.CASCADE)
    color=models.ForeignKey('shop.Color',on_delete=models.CASCADE)
    created=models.DateField(auto_now_add=True)


class Customer(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.user.get_full_name()
    

class Review(models.Model):
    customer=models.ForeignKey(Customer, on_delete=models.CASCADE,related_name='reviews')
    product=models.ForeignKey(Product, on_delete=models.CASCADE,related_name='reviews')
    comment=models.TextField()
    star_count=models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    created=models.DateField(auto_now_add=True)
    


class ResetPassword(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    token = models.CharField(max_length=100)
    used = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.token = self.token or token_urlsafe(50)
        return super().save(*args, **kwargs)

    def is_valid(self):
        not_used = not self.used
        not_expired = (localtime() - timedelta(days=1)) < self.created
        return not_used and not_expired
    
    def get_absolute_url(self):
        return reverse("customer:reset-password", kwargs={"token": self.token})
    

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Contact,Customer,ResetPassword




class ContactForm(forms.ModelForm):
    class Meta:
        fields='__all__'
        model=Contact
        widgets={
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Your name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'Your email'}),
            'subject':forms.TextInput(attrs={'class':'form-control','placeholder':'Subject'}),
            'message':forms.Textarea(attrs={'class':'form-control','placeholder':'Message','rows':'8'}),
        }



class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control',}))
    last_name = forms.CharField(max_length=50,widget=forms.TextInput(attrs={'class':'form-control',}))
    email = forms.EmailField(max_length=50,widget=forms.EmailInput(attrs={'class':'form-control',}))
    username = forms.CharField(max_length=100,widget=forms.TextInput(attrs={'class':'form-control',}))
    password = forms.CharField(max_length=50,widget=forms.PasswordInput(attrs={'class':'form-control',}))
    password2 = forms.CharField(max_length=50,label='Password again',widget=forms.PasswordInput(attrs={'class':'form-control',}))

    def clean(self):
        cleaned_data=super().clean()
        password=cleaned_data.get('password')
        password2=cleaned_data.get('password2')

        if password and password2 and password != password2:
            raise forms.ValidationError('Sifreler eyni deyil!')
        
    def clean_email(self):
        email=self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError('Bu email movcuddur!')
        return email
    
    def clean_username(self):
        username=self.cleaned_data.get('username')
        if username and User.objects.filter(username=username).exists():
            raise forms.ValidationError('Bu username movcuddur!')
        return username


    def save(self):
        cleaned_data=self.cleaned_data
        username=cleaned_data.get('username')
        first_name=cleaned_data.get('first_name')
        last_name=cleaned_data.get('last_name')
        email=cleaned_data.get('email')
        password=cleaned_data.get('password')

        new_user=User.objects.create_user(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
         )
        customer = Customer.objects.create(user=new_user)
        return customer


class PasswordResetForm(forms.Form):
    token = forms.CharField(widget=forms.HiddenInput())
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    password_again = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password Again'}))


    def clean(self):
        cleaned_data = super().clean()
        token = cleaned_data['token']
        username = cleaned_data['username']
        password = cleaned_data['password']
        password_again = cleaned_data['password_again']
        rp = ResetPassword.objects.filter(token=token).first()
        user = User.objects.filter(username=username).first()
        if not user:
            raise forms.ValidationError('This username doesn\'t exist')
        if not rp or rp.user != user:
            raise forms.ValidationError('Process failed')
        
        if password and password_again and password != password_again:
            raise forms.ValidationError('Passwords are not same!')
        
        return cleaned_data
    

    def save(self):
        cleaned_data = self.cleaned_data
        username = cleaned_data['username']
        password = cleaned_data['password']
        user = User.objects.get(username=username)
        user.set_password(password)
        user.save()
        rp = ResetPassword.objects.get(token=cleaned_data['token'])
        rp.used = True
        rp.save()
        return user

customer/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .forms import ContactForm, RegisterForm,PasswordResetForm
from django.contrib.auth import login,logout,authenticate
from .models import WishItem,BasketItem,ResetPassword
from django.contrib.auth.decorators import login_required
from shop.models import Product
from django.db.models import Sum,F
from payment.models import Coupon
from django.contrib.auth.models import User 
from django.core.mail import send_mail
from .tasks import send_custom_celery_mail, send_custom_ordinary_mail
from django.conf import settings

# Create your views here.


def contact(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'contact.html', {'form': ContactForm, 'result': 'success'})
        return render(request, 'contact.html', {'form': form, 'result': 'fail'})
    return render(request, 'contact.html', {'form': form})


def wishlist_view(request):
    wishlist=request.user.customer.wishlist.all()
    total_price=wishlist.aggregate(total_price=Sum('product__price'))['total_price']
    return render(request, 'wishlist.html',{'wishlist': wishlist,'total_price': total_price})

@login_required
def unwish_product(request,pk):
    product=get_object_or_404(Product,pk=pk)
    customer=request.user.customer
    WishItem.objects.filter(product=product, customer=customer).delete()
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def wish_product(request,pk):
    product=get_object_or_404(Product,pk=pk)
    customer=request.user.customer
    WishItem.objects.create(product=product, customer=customer)
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def basket(request):
    basketlist=request.user.customer.basketlist.all().annotate(total_price=F('count')*F('product__price'))
    all_price = basketlist.aggregate(all_price=Sum('total_price'))['all_price'] or 0
    shipping_price = all_price * 0.07
    final_price = all_price + shipping_price
    coupon_code = request.GET.get('coupon')
    coupon_status = None    
    coupon_message = None
    coupon_discount = 0
    coupon_discount_amount = 0
    if coupon_code:
        coupon = Coupon.objects.filter(code=coupon_code).first()
        if coupon:
            is_valid,message = coupon.is_valid(request.user.customer)
            if is_valid:
                coupon_status = 'valid'
                coupon_message = message
                coupon_discount = coupon.discount
                coupon_discount_amount = final_price * coupon_discount / 100
                final_price -= coupon_discount_amount
            else:
                coupon_status = 'invalid'
                coupon_message = message
        else:
            coupon_status = 'invalid'
            coupon_message = 'Bele bir kupon yoxdur'


    return render(request,'basket.html',
    {
    'basketlist':basketlist,
    'all_price':all_price,
    'shipping_price':shipping_price,
    'final_price':final_price,
    'coupon_code':coupon_code,
    'coupon_message':coupon_message,
    'coupon_status':coupon_status,
    'coupon_discount':coupon_discount,
    'coupon_discount_amount':coupon_discount_amount,
    })


def add_basket(request,product_pk):
    if request.method == 'POST':
        size_pk=request.POST.get('size')
        color_pk=request.POST.get('color')
        count=request.POST.get('count')
        customer=request.user.customer
        BasketItem.objects.create(product_id=product_pk, size_id=size_pk, color_id=color_pk,count=count,customer=customer)
        return redirect(request.META.get('HTTP_REFERER'))
    else:
        return redirect('shop:home')
    

def increase_basket_item(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    basket.count=F('count')+1
    basket.save()
    return redirect('customer:basket')

def decrease_basket_item(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    if basket.count==1:
        basket.delete()
    else:
        basket.count=F('count')-1
        basket.save()
    return redirect('customer:basket')

@login_required
def remove_basket(request,basket_pk):
    basket=get_object_or_404(BasketItem,pk=basket_pk)
    basket.delete()
    return redirect('customer:basket')



def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')

        if remember_me:
            request.session.set_expiry(1209600)
        else:
            request.session.set_expiry(0)

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            return redirect('shop:home')
        else:
            return render(request, 'login.html', context={'unsuccessful': True})



def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            customer = form.save()
            login(request, customer.user)
            return redirect('shop:home')
    return render(request, 'register.html', {'form': form})



def logout_view(request):
    logout(request)
    return redirect('customer:login')

    
usd_eq={'AZN':1.7,'TRY':27.1,'EUR':0.92,'USD':1}
def change_currency(request):
    currency = request.GET.get('currency')
    currency_ratio = usd_eq[currency]
    request.session['currency'] = currency
    request.session['currency_ratio'] = currency_ratio
    return redirect(request.META.get('HTTP_REFERER'))



def forgot_password_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user:
            ResetPassword.objects.filter(user=user).update(used=True)
            rp = ResetPassword.objects.create(user=user)
            url = request.build_absolute_uri(rp.get_absolute_url())
            message = f'Please renew your password from this link:{url}'
            subject = 'Renew Password'
            sender = settings.EMAIL_HOST_USER
            # send_mail(subject,message,sender,[email])
            send_custom_celery_mail.delay(subject,message,sender,[email])
            # send_custom_ordinary_mail(subject,message,sender,[email])
            return redirect('customer:reset-password-result',color='success',message='Mail sent successfully')
        else:
            return render(request,'forgot_password.html',{'status':'invalid_user'})
    return render(request,'forgot_password.html')


def reset_password_view(request, token):
    rp = ResetPassword.objects.filter(token=token).first()
    if rp and rp.is_valid():
        if request.method == 'GET':
            form = PasswordResetForm(initial={'token': token})
            return render(request, 'reset-password.html', {'form': form})
        else:
            form = PasswordResetForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('customer:reset-password-result', color='success', message='Password changed successfully')
            return render(request, 'reset-password.html', {'form': form})
    else:
        return redirect('customer:reset-password-result', color='danger', message='This link is broken or already used!')



def reset_password_result_view(request,color,message):
    return render(request,'reset-password-result.html',{'color':color,'message':message})

customer/templates/basket.html
{% extends 'layout.html' %}
{% block main %}
 <!-- Breadcrumb Start -->
 <div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for basket in basketlist  %}
                    <tr>
                        <td class="align-middle"><img src="{{basket.product.images.first.image.url}}" alt="" style="width: 50px;">{{basket.product.title}}</td>
                        <td class="align-middle">${{basket.product.price}}</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-primary btn-minus" href="{% url 'customer:decrease-basket-item' basket_pk=basket.pk %}">
                                    <i class="fa fa-minus"></i>
                                    </a>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{basket.count}}">
                                <div class="input-group-btn">
                                    <a class="btn btn-sm btn-primary btn-plus" href="{% url 'customer:increase-basket-item' basket_pk=basket.pk %}">
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">${{basket.total_price}}</td>
                        <td class="align-middle"><a class="btn btn-sm btn-danger" href="{% url 'customer:remove-basket' basket_pk=basket.pk %}"><i class="fa fa-times"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" name="coupon" {% if coupon_code %}value="{{coupon_code}}"{% endif %} placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
                {% if coupon_status == 'valid' %}
                <p class="text-success font-weight-bold text-center mt-3">{{coupon_message}}</p>
                {% elif coupon_status == 'invalid' %}
                <p class="text-danger font-weight-bold text-center mt-3">{{coupon_message}}</p>
                {% endif %}
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>${{all_price|floatformat}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">${{shipping_price|floatformat}}</h6>
                    </div>
                    {% if coupon_status == 'valid' %}
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Coupon Discount</h6>
                        <h6 class="font-weight-medium">- ${{coupon_discount_amount|floatformat}} ({{coupon_discount|floatformat}}%)</h6>
                    </div>
                    {% endif %}
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>${{final_price}}</h5>
                    </div>
                    {% if final_price %}
                    <a href="{% url 'payment:checkout' %}{% if coupon_status == 'valid' %}?coupon={{coupon_code}}{% endif %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->   
{% endblock main %}

customer/templates/contact.html
{% extends 'layout.html' %}
{% load static %}
{% block main %}
 <!-- Contact Start -->
 <div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                {% if result == 'success' %}
                <div class="alert alert-success" role="alert">Muracietiniz gonderildi!</div>
                {% elif result == 'fail'%}
                <div class="alert alert-danger" role="alert">Muracietiniz gonderilmedi!</div>
                {% endif %}
                <div id="success"></div>
                <form method="POST">
                    {% csrf_token %}
                    <div class="control-group mb-3">
                        {{form.name}}
                        {% if error in form.name.errors %}
                        <p class="help-block text-danger">{{error}}</p>
                        {% endif %}
                    </div>
                    <div class="control-group mb-3">
                        {{form.email}}
                        {% if error in form.name.errors %}
                        <p class="help-block text-danger">{{error}}</p>
                        {% endif %}
                    </div>
                    <div class="control-group mb-3">
                        {{form.subject}}
                        {% if error in form.name.errors %}
                        <p class="help-block text-danger">{{error}}</p>
                        {% endif %}
                    </div>
                    <div class="control-group mb-3">
                        {{form.message}}
                        {% if error in form.name.errors %}
                        <p class="help-block text-danger">{{error}}</p>
                        {% endif %}
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                            Message</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                src="{% static 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd' %}"
                frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock main %}

customer/templates/login.html
{% extends 'layout.html' %}

{% block main %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5 bg-primary p-4 rounded shadow">
                <div class="row">
                    <div class="col-12">
                        <div class="row">
                            <div class="col h3 text-center">Login</div>
                        </div>
                    </div>
                    <div class="col-12">
                        {% if unsuccess %}
                        <div class="text-danger text-center">Username ve ya sifre yanlisdir!</div>
                        {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input id="username" type="text" class="form-control" name="username">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Password</label>
                                <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                            </div>
                            <div class="form-group form-check">
                                <input type="checkbox" name="remember_me" class="form-check-input" id="exampleCheck1">
                                <label class="form-check-label" for="exampleCheck1">Remember Me</label>
                            </div>
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-secondary">Submit</button>
                            </div>
                            <div class="text-dark text-center pt-3">
                                <a href="{% url 'customer:forgot-password' %}" class="text-dark">Forgot Password</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}

customer/templates/reset-password-result.html
{% extends 'layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    <title>Login</title>
{% endblock title %}

{% block main %}
    <div class="container">
        <div class="form-wrapper row p-5">
            <div class="col-6 offset-3 bg-warning p-4">
                <div class="h3 text-dark text-center pb-4 font-weight-bold">Message</div>
                <div class="h2 text-{{color}} text-center">{{message}}</div>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'shop:home' %}" class="btn btn-dark py-2 px-4" type="submit" id="sendMessageButton">Home</a>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

customer/templates/wishlist.html
{% extends 'layout.html' %}
{% block title %}
{% load shop_helper %}
<title>Wishlist</title>
{% endblock title %}

{% block main %}
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a href="#" class="breadcrumb-item text-dark">Home</a>
                    <a href="#" class="breadcrumb-item text-dark">Shop</a>
                    <span class="breadcrumb-item active">Shopping Cart</span>
                </nav>
            </div>
        </div>
    </div>


    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Review</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for wishitem in wishlist  %}
                        <tr>
                            <td class="align-middle"><img src="{{wishitem.product.images.first.image.url}}" alt="" style="width:50px;"><a class="text-dark" href="{{wishitem.product.get_absolute_url}}">{{wishitem.product.title}}</a></td>
                            <td class="align-middle">${{wishitem.product.price}}</td>
                            <td class="align-middle">{% star wishitem.product.get_avg_star %}</td>
                            <td class="align-middle"><a href="{% url 'customer:unwish-product' pk=wishitem.product.pk %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{total_price|floatformat}}</h5>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}